name: agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=2.3
  - pip:
  # For Augogen Framework
      - autogen-ext
      - autogen-agentchat
  # For MCP server
      - mcp[cli]
      - httpx